### ISSUE TITLE
Clean up old extensions during install

### ISSUE THREAD

**Issue by aschn** [stitchfix/nodebook#1]
I had an old copy of `~/.ipython/extensions/nodebook.pyc` lying around that led to an error on the `%load_ext nodebookext` step. Deleting that `pyc` file by hand resolved the issue. If there's a way to remove old extensions during install if filenames change in the future, that would be great!

**Comment by kzielnicki** [comment]
This happened because I did some major refactoring between the internal and public versions of nodebook, which unfortunately requires some incompatibility / manual migration for users of the internal version who want to switch to the public version. It shouldn't come up again in updates to the current project, but if it does I will work on a solution to automating the migration :)
